#!/bin/bash

# This script rebuilds the algorithmically-generated ftml files.

set -e

if [ ! -f wscript ]
then
	echo "Must be in the root of the project"
	exit 2
fi

# configure tests
tests="AllChars Proof Diac Matras Conjuncts"
urls='url(../references/patelN.ttf)=patelR url(../references/patelB.ttf)=patelB url(../references/patelI.ttf)=patelI url(../references/GUJRGir-Regular.ttf)=gujrR url(../references/GUJRGir-Bold.ttf)=gujrB url(../references/GUJRGir-Italic.ttf)=gujrI url(../references/Gir-Regular.ttf)=refR url(../references/Gir-Bold.ttf)=refB url(../references/Gir-Italic.ttf)=refI url(../references/Gir-BoldItalic.ttf)=refBI url(../results/Gir-Regular.ttf)=R url(../results/Gir-Bold.ttf)=B url(../results/Gir-Italic.ttf)=I url(../results/Gir-BoldItalic.ttf)=BI url(../references/NotoSerifGujarati-Regular.ttf)=notoSerif url(../references/NotoSansGujarati-Regular.ttf)=notoSans url(../references/NotoSansGujaratiUI-Regular.ttf)=notoSansUI url(../references/BalooBhai2-Regular.ttf)=baloo url(../references/AnekGujarati-Regular.ttf)=ek  url(../references/Lohit-Gujarati.ttf)=lohit'
ufo='source/Gir-Regular.ufo'

# list all the fonts to test
fonts=''
for url in $urls
do
	fonts="$fonts -s '$url'"
done

echo "Rebuilding ftml files..."
for test in $tests
do
	base=${test,,}
	title="\"${test} auto\""
	ftml=tests/${base}.ftml
	log=tests/logs/${base}.log
	eval tools/psfgenftml.py -q -t "$title" --prevfont references/Gir-Regular.ttf --norendercheck --scale 200 -i source/glyph_data-Gir.csv --xsl ../tools/ftml.xsl "$fonts" -l $log $ufo $ftml &
done
wait
echo "done."
