#!/bin/bash

faces=(Gir)
styles=(Regular Bold Italic)
desc_long="Gujarati script font for all languages using the Gujarati script"

export nlci=$HOME/script/tools
export cs=$HOME/script/charsets
export src=source
source ${nlci}/prepare.bash

source ${nlci}/metadata.bash

rm -f ${src}/*-???*.sfd*
echo "done cleaning up"
