#!/bin/bash

faces=(Gir)
styles=(Regular Bold Italic)
desc_long="Gujarati script font for all languages using the Gujarati script"

export nlci=$HOME/script/tools
export cs=$HOME/script/charsets
export src=source
source ${nlci}/prepare.bash

pushd ${src}
../tools/bold.py Gir-Bold.sfd u0AB9 u0AAA u0ABC u0AC4 u0ACD_u0AB0.rphf
popd

source ${nlci}/metadata.bash

rm -f ${src}/*-???*.sfd*
echo "done cleaning up"
