#!/usr/bin/python3

Vowels = [
    0x0A85,  # GUJARATI LETTER A
    0x0A86,  # GUJARATI LETTER AA
    0x0A87,  # GUJARATI LETTER I
    0x0A88,  # GUJARATI LETTER II
    0x0A89,  # GUJARATI LETTER U
    0x0A8A,  # GUJARATI LETTER UU
    0x0A8B,  # GUJARATI LETTER VOCALIC R
    0x0A8C,  # GUJARATI LETTER VOCALIC L
    0x0A8D,  # GUJARATI VOWEL CANDRA E
    0x0A8F,  # GUJARATI LETTER E
    0x0A90,  # GUJARATI LETTER AI
    0x0A91,  # GUJARATI VOWEL CANDRA O
    0x0A93,  # GUJARATI LETTER O
    0x0A94,  # GUJARATI LETTER AU
    0x0AE0,  # GUJARATI LETTER VOCALIC RR
    0x0AE1,  # GUJARATI LETTER VOCALIC LL
    0x0AE2,  # GUJARATI VOWEL SIGN VOCALIC L
    0x0AE3,  # GUJARATI VOWEL SIGN VOCALIC LL
    ]

Matras = [
    0x0ABE,  # GUJARATI VOWEL SIGN AA
    0x0ABF,  # GUJARATI VOWEL SIGN I
    0x0AC0,  # GUJARATI VOWEL SIGN II
    0x0AC1,  # GUJARATI VOWEL SIGN U
    0x0AC2,  # GUJARATI VOWEL SIGN UU
    0x0AC3,  # GUJARATI VOWEL SIGN VOCALIC R
    0x0AC4,  # GUJARATI VOWEL SIGN VOCALIC RR
    0x0AC5,  # GUJARATI VOWEL SIGN CANDRA E
    0x0AC7,  # GUJARATI VOWEL SIGN E
    0x0AC8,  # GUJARATI VOWEL SIGN AI
    0x0AC9,  # GUJARATI VOWEL SIGN CANDRA O
    0x0ACB,  # GUJARATI VOWEL SIGN O
    0x0ACC,  # GUJARATI VOWEL SIGN AU
    0x0ACD,  # GUJARATI SIGN VIRAMA
    ]

Consonants = [
    0x0A95,  # GUJARATI LETTER KA
    0x0A96,  # GUJARATI LETTER KHA
    0x0A97,  # GUJARATI LETTER GA
    0x0A98,  # GUJARATI LETTER GHA
    0x0A99,  # GUJARATI LETTER NGA
    0x0A9A,  # GUJARATI LETTER CA
    0x0A9B,  # GUJARATI LETTER CHA
    0x0A9C,  # GUJARATI LETTER JA
    0x0A9D,  # GUJARATI LETTER JHA
    0x0A9E,  # GUJARATI LETTER NYA
    0x0A9F,  # GUJARATI LETTER TTA
    0x0AA0,  # GUJARATI LETTER TTHA
    0x0AA1,  # GUJARATI LETTER DDA
    0x0AA2,  # GUJARATI LETTER DDHA
    0x0AA3,  # GUJARATI LETTER NNA
    0x0AA4,  # GUJARATI LETTER TA
    0x0AA5,  # GUJARATI LETTER THA
    0x0AA6,  # GUJARATI LETTER DA
    0x0AA7,  # GUJARATI LETTER DHA
    0x0AA8,  # GUJARATI LETTER NA
    0x0AAA,  # GUJARATI LETTER PA
    0x0AAB,  # GUJARATI LETTER PHA
    0x0AAC,  # GUJARATI LETTER BA
    0x0AAD,  # GUJARATI LETTER BHA
    0x0AAE,  # GUJARATI LETTER MA
    0x0AAF,  # GUJARATI LETTER YA
    0x0AB0,  # GUJARATI LETTER RA
    0x0AB2,  # GUJARATI LETTER LA
    0x0AB3,  # GUJARATI LETTER LLA
    0x0AB5,  # GUJARATI LETTER VA
    0x0AB6,  # GUJARATI LETTER SHA
    0x0AB7,  # GUJARATI LETTER SSA
    0x0AB8,  # GUJARATI LETTER SA
    0x0AB9,  # GUJARATI LETTER HA
    ]

Nukta = [
    0x0ABC,  # GUJARATI SIGN NUKTA
    ]

Virama = [
    0x0ACD,  # GUJARATI SIGN VIRAMA
    ]

Digits = [
    0x0AE6,  # GUJARATI DIGIT ZERO
    0x0AE7,  # GUJARATI DIGIT ONE
    0x0AE8,  # GUJARATI DIGIT TWO
    0x0AE9,  # GUJARATI DIGIT THREE
    0x0AEA,  # GUJARATI DIGIT FOUR
    0x0AEB,  # GUJARATI DIGIT FIVE
    0x0AEC,  # GUJARATI DIGIT SIX
    0x0AED,  # GUJARATI DIGIT SEVEN
    0x0AEE,  # GUJARATI DIGIT EIGHT
    0x0AEF,  # GUJARATI DIGIT NINE
    ]

vowels = list(map(chr, Vowels))
matras = list(map(chr, Matras))
consonants = list(map(chr, Consonants))
n = nukta = list(map(chr, Nukta))[0]
h = virama = list(map(chr, Virama))[0]
digits = list(map(chr, Digits))
